import { Box, Center, Flex, Text, Image } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'

import jujutsu from '../public/jujutsu.png'
import painel from '../public/painel.jpg'


type CardsProps = {
  title?: string
  image?: string
  fundo?: string
}

const Cards = ({ title, image, fundo }: CardsProps) => (
  <Box h="280px" w="240px"
    bgImage={`url(${fundo})`}
    backgroundPosition="center 0"
    // backgroundSize="cover"
    // borderRadius="15px"
    //overflow="hidden"
    className="card card__one"
  >
    <Box className="card__bg">
      <Image src={image} h="110%" w="241px" className="card__img" />
      <Text
        mt="-40px"
        textAlign="center"
        fontFamily="Open Sans"
        color="#FFFFFF"
        fontSize='18px'
        fontWeight="700"
      >
        {title}
      </Text>
    </Box>
  </Box>
)

const cards = document.querySelector(".cards");
const images = document.querySelectorAll(".card__img");
const backgrounds = document.querySelectorAll(".card__bg");
const range = 40;

// const calcValue = (a, b) => (((a * 100) / b) * (range / 100) -(range / 2)).toFixed(1);

const calcValue = (a, b) => (a / b * range - range / 2).toFixed(1) // thanks @alice-mx

let timeout;
document.addEventListener('mousemove', ({ x, y }) => {
  if (timeout) {
    window.cancelAnimationFrame(timeout);
  }

  timeout = window.requestAnimationFrame(() => {
    const yValue = calcValue(y, window.innerHeight);
    const xValue = calcValue(x, window.innerWidth);

    cards.style.transform = `rotateX(${yValue}deg) rotateY(${xValue}deg)`;

    [].forEach.call(images, (image) => {
      image.style.transform = `translateX(${-xValue}px) translateY(${yValue}px)`;
    });

    [].forEach.call(backgrounds, (background) => {
      background.style.backgroundPosition = `${xValue * .45}px ${-yValue * .45}px`;
    })
  })
}, false);

const Home: NextPage = () => {




  return (
    <>
      <Head>
        <title>Trics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Box h="100%" w="100%" bg='linear-gradient(to bottom, #C6426E, #642B73)' justifyContent="center"  >
          <Box className="cards">
            <Text textAlign="left"
              fontFamily="Open Sans"
              color="#eb285d"
              fontSize='32px'
              transform='translateZ(35px)'
              fontWeight="bold"
              mb="6px"
            >
              NFT's
            </Text>
            <Text textAlign="left"
              fontFamily="Open Sans"
              color="#3e3e42"
              fontSize='16px'
              transform='translateZ(25px)'
            >Mais Populares</Text>

            <Cards fundo={painel.src} image={jujutsu.src} title={'Satoru'} />
          </Box>
        </Box>
      </Flex>
    </>
  )
}

export default Home
