import { Box, Flex } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Original: NextPage = () => {

  const cards = document.querySelector(".cards");
  const images = document.querySelectorAll(".card__img");
  const backgrounds = document.querySelectorAll(".card__bg");
  const range = 40;
  
  // const calcValue = (a, b) => (((a * 100) / b) * (range / 100) -(range / 2)).toFixed(1);
  const calcValue = (a, b) => (a/b*range-range/2).toFixed(1) // thanks @alice-mx
  
  let timeout;
  document.addEventListener('mousemove', ({x, y}) => {
    if (timeout) {
      window.cancelAnimationFrame(timeout);
    }
      
    timeout = window.requestAnimationFrame(() => {
      const yValue = calcValue(y, window.innerHeight);
      const xValue = calcValue(x, window.innerWidth);
  
      cards.style.transform = `rotateX(${yValue}deg) rotateY(${xValue}deg)`;
  
      [].forEach.call(images, (image) => {
        image.style.transform = `translateX(${-xValue}px) translateY(${yValue}px)`;
      });
  
      [].forEach.call(backgrounds, (background) => {
        background.style.backgroundPosition = `${xValue*.45}px ${-yValue*.45}px`;
      })
    })
  }, false);

  return (
    <>
      <Head>
        <title>Trics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100%" w="100%"  bg='linear-gradient(to bottom, #C6426E, #642B73)'>
      <div className="cards">
        <h3>Movies</h3>
        <h1>Popular</h1>
        <div className="card card__one">
          <div className="card__bg"></div>
          <img className="card__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/62105/3dr_mono.png" />
          <div className="card__text">
            <p className="card__title">Princess Mononoke</p>
          </div>
        </div>
        <div className="card card__two">
          <div className="card__bg"></div>
          <img className="card__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/62105/3dr_chihiro.png" />
          <div className="card__text">
            <p className="card__title">Spirited Away</p>
          </div>
        </div>
        <div className="card card__three">
          <div className="card__bg"></div>
          <img className="card__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/62105/3dr_howlcastle.png" />
          <div className="card__text">
            <p className="card__title">Howl's Moving Castle</p>
          </div>
        </div>
      </div>
      </Flex>
    </>
  )
}

export default Original
